

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: 'user'
    password: 'admin'
    driver-class-name: org.postgresql.Driver
  sql:
    platform: postgres
    init:
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql
      mode: always
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      # Change to none for production
      ddl-auto: create-drop